### PR TITLE
Fix/filter functionality

### PR DESCRIPTION
**Pull request by AlinaPalyvoda**

### CODE REVIEW

**Review by HIMDanny — COMMENTED** [review]
- Price filter does not work correctly:
image

    - Tours do not update when only price filter is active
- Don't think that season filter work correctly as it is showing the same tours whatever season is chosen
- I think when you use filter it is better to update only tours instead of reloading a whole page

**Comment by AlinaPalyvoda** [comment]
> * Don't think that season filter work correctly as it is showing the same tours whatever season is chosen

**Comment by AlinaPalyvoda** [comment]
> * Price filter does not work correctly:
Bug fixed

**Comment by AlinaPalyvoda** [comment]
> * Price filter does not work correctly:

Bug fixed

**Comment by AlinaPalyvoda** [comment]
> * Don't think that season filter work correctly as it is showing the same tours whatever season is chosen

Filtered tours are displayed correctly.
Since most tours list the season as "all-season", they will also show up for any other season. Therefore, it seems that the filter is not working.

**Review by HIMDanny — APPROVED** [review]

**Review by Ahmed-Fahmy-Dev — APPROVED** [review]

**Pull request merged**
